define({
    TYPE_HUMAN: 1,
    TYPE_NPC: 2,
    TYPE_PLAYER: 3,
    TYPE_NO_TYPE: 10,

    TERRAIN_ROAD: 1,
    TERRAIN_LAND: 2,
    TERRAIN_WATER: 3,


    WORLD_SIZE: 256,
    ZOOM: 18,
    PIXEL_SIZE: 256 / 18 / 18,
    EARTH_RADIUS: 6378.137,

    QUADTREE_NODE_LIMIT: 20,
    QUADTREE_LEVEL_LIMIT: 20

})

